version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - yum install wget unzip
      - wget https://releases.hashicorp.com/terraform/1.2.9/terraform_1.2.9_linux_amd64.zip
      - unzip ./terraform_1.2.9_linux_amd64.zip -d /usr/local/bin      
      

  build:
    commands:
      - terraform init
#       - terraform plan
