version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - yum install wget unzip
      - wget https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip
      - unzip ./terraform_0.12.2_linux_amd64.zip -d /usr/local/bin      
      - terraform -v
      

  build:
    commands:
      - terraform init
#       - terraform plan
