version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
        # install yum-config-manager to manage your repositories
      - apt-get update && sudo apt-get install -y gnupg software-properties-common 

        # use yum-config-manager to add the official HashiCorp Linux repository
        #yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

        # install terraform
      - apt-get install terraform 

        # verify terraform is installed
      - terraform --version

  build:
    commands:
      - terraform init
      - terraform validate
      - terraform plan
