version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - ls /etc/yum.repos.d/      
      - yum install terraform -y
      - terraform --version
      

  build:
    commands:
      - terraform init
      - terraform plan
