version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - yum update -y
      - yum install -y yum-utils
      - wget https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
      - yum -y install terraform
      - terraform --version
      

  build:
    commands:
      - terraform init
      - terraform plan
